### ISSUE TITLE
Build is failing - Deprecated Java 11

### ISSUE THREAD

**Issue by PawelPodkalicki** [SonarSource/sq-com_example_standard-sqscanner-travis#13]
Hi,
My builds were failing due to deprecated Java version by sonar-scanner. I found this project as an example of working build which apparently does not work 😢. I found a fix to my builds which probably can be used in this project.

This project's build is failing since 18th January. I suppose that the source of the problem is that sonar-scanner needs Java 17. It must be set in travis.

In my project setting `jdk: openjdk17` was not sufficient. I had to explicitly set Java version.

```
      before_script:
        - export JAVA_HOME=/usr/local/lib/jvm/openjdk17
        - export PATH="$JAVA_HOME/bin:$PATH"
        - java --version
```

**Comment by 7PH** [comment]
Hello @PawelPodkalicki , this was fixed in this PR https://github.com/SonarSource/sq-com_example_standard-sqscanner-travis/pull/15 , so I'll close this issue, thanks for reporting!
